version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    groups:
      force-graph:
        patterns:
          - "three"
          - "3d-force-graph"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
