version: '3.8'

services:
  meta-infinite-graph:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # - "${ROLES_DIR:-./roles}:/usr/share/nginx/html/roles:ro"
      - ./:/usr/share/nginx/html
    ports:
      - "8000:80"
